info:
    app:
        name: Environment Manager REST API
        description: An application that provides endpoints to help the user in easy provisioning of environment and manage large infrastructure.

server:
    port: 9000
    servlet:
        context-path: /provisioning
spring:
    security:
        user:
            name: AUTOMIC
            password: AUTOMIC
    datasource:
        driverClassName: org.postgresql.Driver
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:postgres}
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:provisioning_rest_api}
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        hibernate:
            jdbc:
                lob:
                    non_contextual_creation: true
            ddl-auto: validate
            dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
    mvc:
        throw-exception-if-no-handler-found: true
        static-path-pattern: /swagger*
    resources:
        static-locations: classpath:/swagger*

logging:
    file: logfile.log
    level:
        root: INFO
# Workaround for a bug of Swagger that raises the warning message when there is no default value for the integer API param
        io:
            swagger:
                models:
                    parameters:
                        AbstractSerializableParameter: ERROR

management:
    endpoints:
        web:
            base-path: /api/v1/management
            exposure:
                include: health, info, logfile


emPath: ${EM_PATH:/tmp/.em}
rest-api-prefix: api
rest-api-version: v1
rest-api-paging-max-results: 20